### ISSUE TITLE
Suggestion: Add workspace.cursorPos and workspace.cursorPosChanged

### ISSUE THREAD

**Issue by ItsGabeReal** [RubixDev/kwin-types#1]
These two properties were added to the KWin API in [this commit](https://github.com/KDE/kwin/commit/96cfc411f0762f4f5cd1b8396d5a81d8d40a85b2).

They can be added to the `WorkspaceWrapper` class in kwin.d.ts:

### cursorPos
```
/**
 * The current position of the cursor.
 */
readonly cursorPos: QPoint
```
### cursorPosChanged
```
/**
 * This signal is emitted when the cursor position changes.
 * @see {@link cursorPos}
 */
readonly cursorPosChanged: Signal<() => void>
```

**Comment by RubixDev** [comment]
Would you be able to turn this into a PR?

**Comment by ItsGabeReal** [comment]
Sure thing: #2
